### ISSUE TITLE
pip install option

### ISSUE THREAD

**Issue by emiltoft** [pyomeca/ezc3d#111]
Hi
Good work on developing a c3d-manager. There is defiantly a need for it since BTK development is ended - does not support python3. Are you thinking of including a pip implementation as well (as a supplement to Conda? It would be very helpfull.

Kind regards,
Emil

**Comment by pariterre** [comment]
Dear @emiltoft 
This is indeed something I am considering. I am not hugely familiar with pip so I have to make so research (especially for the fact that the backend is in C++ and therefore needs to be built before it is deployed. 

I'll let you know soon if I am successful in my research!

**Comment by blikpils** [comment]
Hey, i am wondering if there is any update to this. 

A pip instal would be greatly helpful, even if the version is slightly out of date!

**Comment by melund** [comment]
Creating wheels of packages with C extensions is really a pain. It is just hard. And even they we mange to make one, it is not guaranteed to work because pip doesn't control the environment and libraries which the user has otherwise installed. 

This is what conda was created to solve. So if you use any scientific python libraries I highly recommend using conda. 

Maybe we could use [conda press](https://github.com/conda-incubator/conda-press) to create wheels from the conda packages. That may be the easiest way to get wheels.

**Comment by pariterre** [comment]
Hi everyone, 
I was keeping this open so I would (maybe) someday find a way for this. So during the year I revisited this issue, but always arrived at the same conclusion, which was @melund described it perfectly : `This is what conda was created to solve. So if you use any scientific python libraries I highly recommend using conda.`

I will therefore stop trying this. I can safely say now, that there won't be pip package of ezc3d. Sorry about that...
