### ISSUE TITLE
Python installation without conda

### ISSUE THREAD

**Issue by mrrezaie** [pyomeca/ezc3d#115]
Hi,
I'm interested in using EZC3D as an alternative to BTK in python 3.7 in windows os.
I'm not an advanced python user and don't use Miniconda or anaconda (due to some incompatibilities). Would you please tell me how I can install EZC3D without conda? 
I was looking for a file named setup.py but I couldn't find any. 
Regards

**Comment by pariterre** [comment]
Dear @kernalnet,

The Python binder, is actually just a binder. Meaning that the core is written in C++. Thus, you have to compile it first. The procedure for that highly depends on which OS you use. In all cases, unless you have some experience in, it may be a bit complicated.

Therefore, I strongly suggest the use of Anaconda. If you really can't, you still can go to anaconda.org and find the binaries of ezc3d and extract the folder at the right place, that is 'site-packages' of the Python folder (this should works fine on Windows, but I doubt it would make it easier on Linux, and I suspect the same on Mac, because of runtime-path that won't be updated).

If you want to compile the library yourself. This is not actually something hard to do. You can have a look at the ezc3d main page on GitHub where the ReadMe is. If you need assistance, I would need to know what is your OS so I can help!

Have a good day!
