### ISSUE TITLE
setting first frame

### ISSUE THREAD

**Issue by mureva** [pyomeca/ezc3d#135]
I have point data which I have managed to write to a .c3d file. Now I realise that to make it line up with data from another source which has a non-zero "firstFrame", thus I need to set the "firstFrame" in my data.

I have tried c3d.header().firstFrame(n) but get a compile error because c3d.header() returns a const reference.
So I instead changed my code so that instead of calling c3d.frame( newFrame ) I would call c3d.frame( newFrame, indx+offset ). However, once all the frames have been added, if I call c3d.header().firstFrame() then I get back 0, and although Mokka shows the right number of frames in my file, I stop seeing the points.

Suggestions?

**Comment by pariterre** [comment]
Hello @mureva !

As for the code you provided, it seems that you are using the C++ API? I will assume that for my answer :)

Header should not be changed manually since it is mostly updated via the parameters. Still there are some interface which are provided. Have you tried the `setFirstFrame` interface? That would be to set your c3d with this interface.
```C++

#include <vector>
#include "ezc3d_all.h"

int main()
{
    ezc3d::c3d c3d("c3dExampleFiles/Qualisys.c3d");
    c3d.setFirstFrame(10);
}
```
This should set the first frame to 10. If it does not, that is probably a bug that I will have a look at!

**Comment by mureva** [comment]
Thanks - I didn't see that method mentioned in the online docs, guess they must be out of date(?)
