### ISSUE TITLE
RuntimeError: Type 1 and 3 is not supported yet

### ISSUE THREAD

**Issue by nikorose87** [pyomeca/ezc3d#137]
Hi there,

I am trying to use your package with python. It looks interesting. However, when I try to read the force platform data. It throws the following:

> RuntimeError: Type 3 (and 7) is not supported yet, please open an Issue on GitHub for support.

I assume there is an issue with this platform types but the question is when could you include these ones?

By the way, I am using type 3 platforms.

Thank you.

**Comment by pariterre** [comment]
Hi @nikorose87 
Yep, I do not support yet all the platform types, since I could not find examples to test the implementation for the reading (and preferred to return an error than bad results!). So if you are willing to share your C3D with me, I can have a look.

Please note, that I am currently half way through of a two weeks important exam related to my PhD and therefore I won't be able to have a look until at least next Wednesday :(

**Comment by nikorose87** [comment]
Thanks @pariterre 

In fact, I am reusing data from the literature, here you can find data to make robust your libraries. I am sharing you the link with the specific data of my study, which is type 3.

[https://data.mendeley.com/datasets/b48n46bfry/1](https://data.mendeley.com/datasets/b48n46bfry/1)

I understand your situation, I can wait for that.
Thanks in advance.

**Comment by pariterre** [comment]
This issue was actually discussed in #138

**Comment by pariterre** [comment]
Hello! 
I forgot to tag the PR that was solving this! #141 
Hope you knew that it was solved!
