### ISSUE TITLE
ValueError: USED parameter is not an INT

### ISSUE THREAD

**Issue by nikorose87** [pyomeca/ezc3d#138]
Hi again, 

Sorry for interrupting,

In the python interface the error in the issue title is displayed, When I check the value type of the USED section of the FORCE_PLATFORM, It shows that is a byte.

![image](https://user-images.githubusercontent.com/14098755/89700859-d7fa8100-d8ff-11ea-8a35-8e90723e0f0f.png)

How can I solve this issue and continue with the force platform reading?

Thank you

**Comment by pariterre** [comment]
Dear @nikorose87 
Thanks for reporting the error. Your C3D file doesn't seem to be compliant to the C3D standard. Still, I think it makes sense to be able to read it no matter what ;)

This is a very quick fix, but I'd like to test it before calling it solved. Could you provide me with a C3D file that I could test? You can send it by mail (so I am the only one to get it). If it is a problem for you, I can send commit the fix and you can build ezc3d for yourself and test the fix for me.

Thanks!

**Comment by pariterre** [comment]
This refers to the PR #139

**Comment by pariterre** [comment]
I've had a look at your C3D and I made the fix.
However, there is the use of Type-1 force plate that ezc3d don't support yet. 

I have another Issue for that, that was open last week, as I said to him, I am currently in the middle of a huge 3 weeks exam. If it is okay for you, these two issues will be my priority after the exam!

**Comment by nikorose87** [comment]
I think I'm the same person who asked for the type 3 platform :D

**Comment by pariterre** [comment]
Haha right! Didn't notice!
It seems that you are currently digging into exotic C3D files hahahaha!
That will make a nice improvement for ezc3d, sry that I can't be more reactive coding your needs :(

**Comment by pariterre** [comment]
@nikorose87 
Hi there! I was having a second look on my implementation of the type1 reading and somethings is odd. Currently the behavior ezc3d mimics the one from BTK. However, I started to doubt the BTK implementation. The Free moment, as returned by BTK is not 0-0-Tz, it has value on the first 2 axes. 

It may correct, but I wanted to confirm that with visual confirmation (that is, plotting on matlab the c3d so I can be sure everything is right :) ). And doing so, I've noticed that the force platform 2, 3 and 4 and randomly placed (with 1e25 values in it). I just wanted to confirm with you that the c3d you provided me doesn't have 4 force platform, but only 1

Thanks :)

FYI, I've done my big exam yesterday so I am now back in the game of coding ;)

**Comment by nikorose87** [comment]
Hi @pariterre, thanks for making better this app. I am asking to the researcher why the C3D recognizes 4 force platforms. However, when I see the reactions, only one force platform is displaying the force.

Thus the answer may be affirmative, only one is working.

**Comment by pariterre** [comment]
Thanks for you answer.
It turns out that both of your C3D has very specific problem to solve (https://github.com/opensim-org/opensim-core/issues/2860). I've asked OpenSim to discuss this. 

Since, it will affect your results, if I were you, I would definitely follow what happens (in all cases, I'll keep you posted). The main issue with the Type-1 file is that it has its gravity Y-oriented which is not common at all for C3D. It makes the computation of the Moments wrong. 

When I have discussed this with them, I let you know!

**Comment by nikorose87** [comment]
Thanks, I am following that discussion.

**Comment by pariterre** [comment]
Hi @nikorose87 !
I will close this issue since the name doesn't relate much anymore with the current problem. I move this to #137
