### ISSUE TITLE
non latin character fails

### ISSUE THREAD

**Issue by aaa34169** [pyomeca/ezc3d#149]
Hello

i can t read data from filename including a non-latin character on Windows 10.
That should be transparent.  

I got similar issue with my own version of Btk compiled in python 3.7. 
that work on Linux, not windows !

I am struggling to fix this issue and think that come from a windows settings. 

i will be glad you help me 

cheers 

Fabien

**Comment by pariterre** [comment]
Dear @aaa34169 / Fabien
Is that possible to provide me with a file example that crashes? If not, maybe just to tell me in which elements the non-latin characters are stored (for instance, point or analog names) and if you are aware if they were stored as ASCII or UTF-8 characters

Thanks for reporting the bug!

**Comment by aaa34169** [comment]
dear pariterre, 
You can test by yourself. 
Just change the filename of one of your c3d by including an accent : like "monC3dAccentué.c3d" 
then try to read it again

regards

Fabien

**Comment by pariterre** [comment]
Hi again,
I've had a look a this but it seems to be an unfixable problem. The reason is that it entirely depends on the format file (UTF8 or ANSI) of the original file that calls ezc3d*. Since I have no way to know what is the format of this particular file (which is basically up to the user to define), I cannot properly convert the filename string to UTF16 which is required by Windows. 

For instance, if I try to always converting the filename from UTF8 to UTF16, the UTF8 files will open (Hurray!). However, ANSI files won't open anymore (Bummer...). If on the other hand I do not convert any file, then ANSI files will open but not the UTF8. But as I said, I cannot know what is the format of the source file that called ezc3d, so I don't know what is the format of the filename string passed to ezc3d. The best guest I can make is to assume that is it the same as the system. 

The solution is basically to make sure that the source file matches the operating system's encoding. If you need to convert a file, I would suggest the use of notepad++. Converting your source file into the same encoding as the system (or changing the encoding of Windows to UTF8) should do the trick.

I am sorry that I cannot help more... :-(
If you find a better idea, I will be happy to try it!

* Please note, when I say "source file that calls ezc3d" I do no mead the actual c3d, but the file where the line `ezc3d::c3d("path_to_c3d_with_french_characters.c3d")` appears

**Comment by pariterre** [comment]
This issue was discussed again as I gave another tried today. I arrived at the same conclusion (#170). The PR #171 provides a better error message when this happens in Python
