### ISSUE TITLE
Ezc3d Parameter Group - Interference with Vicon Nexus

### ISSUE THREAD

**Issue by clemensneu98** [pyomeca/ezc3d#162]
I have an issue regarding using ezc3d in combination with Vicon Nexus 2.10.2. When i change Labels via Python, a new subject appears on the user interface where all the parameters are stored to instead of the old subject. I assume this could be due to the fact that ezc3d changes the structure of the group parameters inside the c3d-file and Vicon Nexus may open and store parameters of the group "POINT" and "ANALOG" before the group "SUBJECTS".  Is anything known about this issue? Or is there a way to change parameters while keeping the original order in the file?

Thank you for any help,
Clemens

**Comment by pariterre** [comment]
Hi @clemensneu98 
Sorry I completely missed this issue... 
Ezc3d is not supposed to change the core of a c3d... That said, it is not impossible that Vicon makes some assumptions in regard of their way of implementing a c3d. Could you send me a small example of a script (and maybe a file if possible) that generates this issue :)

**Comment by clemensneu98** [comment]
Hi @pariterre 
To come back to the issue, here is an example of a c3d-File and the python commands used to change the labels. In the raw c3d file the SUBJECT-parameter-group is at first position. When running ezc3d parameter groups like POINT and ANALOG are suddenly above the SUBJECT group when analyzing the file with a viewer.
[c3d_LabelChange.zip](https://github.com/pyomeca/ezc3d/files/5486126/c3d_LabelChange.zip)

**Comment by pariterre** [comment]
Dear @clemensneu98 
Thanks for the file, I was wondering if you could provide me with the original file also (and not only the one produced by ezc3d). 
The reason is that the order in parameter is actually irrelevant. C3D standard does not prescribe a specific order, actually you can even fill a group of parameter before declaring that specific group. This is unnecessary complicated for the programmer, but is unfortunately part of the standard.

In the case of ezc3d, when it creates a new c3d, it first creates all the required group and their respective required parameters and then fill them with the values of the c3d to copy. Afterwards, it creates the optional groups and parameters. This is why POINT and ANALOG jump on top, since POINT and ANALOG are required by standard, while subject was created by Vicon and is not part of the c3d standard. This would be surprising though, unless Nexus is not compliant with c3d standard (which is totally possible), that this causes the problem. I would therefore would like to compare the rest of the file to spot any differences elsewhere. If this is the only difference, I will maybe have to rethink my copy strategy...

**Comment by clemensneu98** [comment]
Hi @pariterre 
The file I sent you was actually the original file, that does not cause problems with Nexus. In the picture attached you can see its internal structure. Maybe the error comes from the way Nexus is accessing and storing values. I believe that Nexus might scan for the SUBJECT group first and afterwards store the values of the POINT and ANALOG group to the previously found subject. In case a subject is not found before the point and analog group are accessed, all values are stored to a new virtual subject. The only explanation I can find for this issue happening, would be that Nexus depends on always needing the same file structure, but I might be wrong.

Thank you for your help,
 Clemens

![c3dStructure](https://user-images.githubusercontent.com/73271615/99652340-fff99480-2a57-11eb-9648-b74b1600d5fa.PNG)

**Comment by pariterre** [comment]
Hi @clemensneu98 
Sorry again for my late response, I have been crazy busy lately. 

I think you are right that Nexus expect a specific file structure (even though this is not necessary in a laid c3d file). That would ensure that users don't mix up c3d between different companies... So that may be something they even would not mind..

I'll try to add a flag for the write function so it can be done in Nexus order. I'll let you know, it should not be too long to code!

**Comment by pariterre** [comment]
Dear @clemensneu98 
I could remotely get access to a Nexus! I tried to replicate the error, but I am not sure what you mean. When I create new file from the one you provided, I actually get only one subject 
![exemple](https://user-images.githubusercontent.com/17518525/101407619-223d4000-38a9-11eb-92ed-39671c375e2a.png)
Did you mean elsewhere? This is Nexus 2.8.1, maybe there is a difference since, I'll ask our administrator to install a newer version of Nexus. 

If you think it is easier, we can set a zoom call during the week. I am free in the morning GMT-5. You can email me :)

**Comment by pariterre** [comment]
Hi @clemensneu98 !
I tried your code with Nexus 2.10.x and did not have problem reading. I changed few things recently, maybe it fixed the problems!

Could you confirm that the version 1.3.8 still have issues?

**Comment by clemensneu98** [comment]
Hi @pariterre!
Thank you for still dealing with this issue! Sadly i also forgot to check for your responses lately. I am currently also working with Nexus 2.10.  The fact that it seems to work for you is indeed confusing. I will have a chance to try out the new version on Wednesday next week and will give your more information on the possible errors.

Thanks again for your time and support,
Clemens

**Comment by pariterre** [comment]
@clemensneu98 
Did you have a change to test the new version? :)
