### ISSUE TITLE
Problem when exporting too many points

### ISSUE THREAD

**Issue by ANaaim** [pyomeca/ezc3d#167]
Hi everyone, 

I was working with c3d file with a large number of point stocked inside and when i tried to add (also a lot) of point to check if my inverse kinematic was working correctly I had a strange behavior. The point were effectively registred in the c3d (i was able to find their movement in mokka) however almost all the point (excepte the 10 first if i remember correctly) were not named correctly  (unamesXX)

Is this behavior known ? Or it might be due to mokka ?

I can send the data if needed, 

Best regards,

**Comment by pariterre** [comment]
Dear Alex,
It is not expected, but definitely not surprising. The c3d format was not originally able to store more than 255 points. It can be push by some kind of hack, but is not standard. So I don't have proper tests yet to cover this! 

 Sending me a c3d with a minimal failing example code that generates the problematic c3d will help me diagnose the problem for sure!

**Comment by pariterre** [comment]
Dear @ANaaim 
I am unable to reproduce the error you are experience. Are you using a previous version of ezc3d (currently 1.3.7). Because before this particular version, ezc3d was not able to properly handle more than 255 markers, but is now able. If you are using a previous version, it could explain why it is not working. 

FYI, because of that, the script you sent me has a bug in it: 
```python 
points_names_dynamic = acq_dynamic['parameters']['POINT']['LABELS']['value']
```
is not the sole places where labels are stored. `acq_dynamic['parameters']['POINT']['LABELS2']['value']` is also one (and more generally any number after the LABELSX, assuming there are more than X multiples of 255 points in the C3D). Unfortunately, by design, C3D would not let us put everything in one place (for instance all in ['POINT']['LABELS']) and it is therefore up to the user to retrieve the point names...
In your code, changing the aforementioned line by
```python
points_names_dynamic = acq_dynamic['parameters']['POINT']['LABELS']['value'] + acq_dynamic['parameters']['POINT']['LABELS2']['value']
```
(and adjusting the rest of the code accordingly) solves the issue

**Comment by pariterre** [comment]
Dear @ANaaim 

```python
acq_dynamic['parameters']['POINT']['LABELS']['value'] = new_name
acq_dynamic['data']['points'] = new_array
del acq_dynamic['parameters']['POINT']["LABELS2"]
del acq_dynamic['data']["meta_points"]

acq_dynamic.write('errorc3d.c3d')
```
Please note that after our discussion, I've decided to make things a bit easier when changing markers. Now, you can completely delete the "meta_points" and let ezc3d create a valid new one (this is of course destructive, but it is unlikely that you ever will need residuals or camera_masks). 

Please note also that now, the error message for LABEL that does not match nb_points was modified so it reads like this `"'c3d['parameters']['POINT']['LABELSX']' must have the same length as nPoints of the data."`
which is LABELS with an X so hopefully it will ring some bells when one uses more than 255 points!

The PR related is #171 
I will push to conda soon 

Enjoy
