### ISSUE TITLE
Non utf8 character in metadata does not work when rewriting on the c3d. 

### ISSUE THREAD

**Issue by ANaaim** [pyomeca/ezc3d#170]
Here in the c3d in their is in one of the metadata (Subject.diagnostic) the following text : Hémiparésie which make impossible to rewrite directly the c3d.

Best regards,
[03489_05293_20201029-GBNNN-VDEF-07.zip](https://github.com/pyomeca/ezc3d/files/5690386/03489_05293_20201029-GBNNN-VDEF-07.zip)

**Comment by pariterre** [comment]
Dear @ANaaim 
After investigating, it would be highly complicated to take care of this, mostly because it depends on the settings of the computer that created the c3d file, which is of course impossible to know.
I could create some specific snippet for your french, but that would not make much sense.

Since it is a python issue, I suggest that you make sure you are using only the ASCII from 0 to 127 in your Vicon. As an alternative, you can use without issue proper UTF-8. I am not sure though how other software will work with that. 

The error message when converting fails now provide the GROUP and PARAMETER in which the conversion failed, which should help the user (#171)

Thanks for reporting!

**Comment by aaa34169** [comment]
If you re under windows 10,  there is a checkbox (enable beta utf8) in the regional settings you can enable . 
That fixed issues with non latin character when i read  c3d or any file either with Btk or opensim4.1.

regards 

Fabien
