### ISSUE TITLE
add new event python

### ISSUE THREAD

**Issue by AnthoSp** [pyomeca/ezc3d#176]
Hello,
I'm sorry to bother you. I am a new user of EZC3D. Many thanks for your great work. Your library allows me not to be dependent on btk on matlab anymore. For a research project (code on python) I have to :
Adding events to a c3D that already has events.
Create events to a c3D that doesn't have events.

I have some difficulties to understand how to do this. Also I don't code in C++, I have some difficulty understanding the documentation. Also I don't know anyone in my lab who uses ezc3d.  I wanted to know if you had a piece of code that I could see how to do.
Thanks in advance
 Anthony

**Comment by pariterre** [comment]
Dear @AnthoSp,
Thanks for your question!

The easy way to add a new parameter in Python is to use the dedicated function, as demonstrated by the following snippet :
```python
import ezc3d
c = ezc3d.c3d("path_to_c3d.c3d")
c.add_parameter("NameOfGroup", "NameOfParameter", [val1, val2, val3], "The description of the parameter")
```
So you can replace `"NameOfGroup"`by `"EVENT"` and then fill all the required parameters.
Unfortunately, EVENT is not a required group (it is a suggested group) for C3D. This means that there is not any certainty in regard of what is required as parameters nor how a specific software uses them. According to the C3D documentation (p. 117-119) the Parameter that you probably have to declare ("NameOfParameter") are
USED, CONTEXTS, LABELS, DESCRIPTIONS, TIMES, SUBJECTS, ICON_IDS, GENERIC_FLAGS
In my opinion USED, LABELS, TIMES and SUBJECTS are probably the only one required.

Please note that for some reason, C3D header also declares Event. Unfortunately, there is no automatic way to fill the header... If your software uses the header declared event instead of the parameters one, please reach me again, I'll try to update ezc3d so it reads the parameters to properly fill the header (I'll probably need a c3d from you)!
