### ISSUE TITLE
[JOSS review] comments about the README.md

### ISSUE THREAD

**Issue by modenaxe** [pyomeca/ezc3d#183]
Few comments about the documentation on the README.md

- [x] there is a misspell in 'developping' at some point
- [x] Could you add a Table of Content? It would be very helpful for navigating the content of the README. You can generate one automatically in seconds if you use the Code editor and a Markdown plugin, for example, or some online tools.
- [x] I would explicitly add the API documentation in the README, rather than have it just as link on the side bar of the repository.
- [ ] is there any plan to add documentation for MATLAB and Python [as BTK has](http://biomechanical-toolkit.github.io/docs/Wrapping/Matlab/_tutorial.html)? That would be extremely helpful for non developers.
- [x] I would include a link to the Youtube video showing how to install ezc3d in the MATLAB readme documentation

Thank you,

Luca

**Comment by pariterre** [comment]
All done!
For the documentation, it is actually already done in the ReadMe. Since the binders are actually interfaces (and not simply binders...), it is proper Python or Matlab structures that are passed to the user. Therefore, from the user point of view, it is simplified to the point that what is described in the ReadMe, even though it seems light, is the actual whole story...

**Comment by modenaxe** [comment]
I see. Good point!
