### ISSUE TITLE
[JOSS review] MATLAB memory management and data format choices

### ISSUE THREAD

**Issue by modenaxe** [pyomeca/ezc3d#184]
Just a question out of curiosity. BTK was managing the MATLAB memory in such a way that it required cleaning it with btk.DeleteAcquisition() at the end of the use (not compulsory but preventing crashes when batch processing large files).
Does ezc3d have the same issue or deals with it differently and the c3d contents are 100% manageable through MATLAB, e.g. the memory is cleaned using the `clear` function on the variable created by `ezc3dRead`?

**Comment by pariterre** [comment]
The way BTK did the memory management is actually interesting. They stored the data in one place and access it at will. However, it implies to dereference a pointer each time you want to access the data. Moreover, they did not provide a true Matlab interface (it is merely an accessor to internal function). It has the advantage to be as efficient as the C++ core. 

Ezc3d one the other hand stick the data to its respective structure (Point or Analog). Therefore, I could not go the same way (which is retroscpectiveley I think was a good thing!). When you load a file, a native Matlab structure (and it is the same in Python) is created and filled with the data. This means that the data are once loaded in ezc3d and then copied to the Matlab structure. This is less efficient (since it copies all the data), but allows for internal memory management instead of a user one. The same is done when writing. The Matlab structure is parsed into a ezc3d class and then write on the disk. Again, this is slower, but much less error prone for the user. 
Please note that when I say less efficient, I talk about time you will ever notice unless you have tens of million of data and even so, I timed BTK and ezc3d and are in the same range, ezc3d being slightly faster because it takes advantage of C++11 and C++14 structures.

**Comment by modenaxe** [comment]
Thank you @pariterre this is very interesting. I take the occasion to ask about another unusual point I have noticed: points are read as (XYZ x N_POINTS x N_FRAMES) while analogs as (N_FRAMES x N_CHANNELS). Would have been more consistent to have N_FRAMES as first dimension also on for the Points, e.g. (N_FRAMES x N_POINTS x XYZ )?

**Comment by pariterre** [comment]
Haha! This is my internal eternal crisis!
For me, n_frames should always be the 3rd dimension, no matter what. Unfortunately, the C langage stores the data in column, which makes it (ever so slightly) more efficient to have the column as the first dimension if your goal is to print individual points...

Still, I think it makes much more sense to have: TYPE x N_ELEMENT x N_FRAMES. So this is how I first wrote the `pyomeca` (another biomechanics library that I am working on in Python) Marker3d AND Analogs. Therefore, the analogs are (1 x n_analogs x n_frames)... which now feels weird... and is not ideal for plotting efficiency. I kept the same idea on Matlab. It could have been an idea to have is as you suggested (N_FRAMES x N_POINTS x XYZ) but I cannot wrap my head around the fact that XYZ are not the first dimension, and second ezc3d was first designed to suit my lab needs, where I coded everything else with the XYZ as first dimension conversion hahaha! 

So it is mainly a historical for our lab (because of me), and a profound dislike of not having XYZ first

**Comment by modenaxe** [comment]
I asked because it always generated an awkward moment also for me when I have to process data! I fell better that I am not the only one! :D
For me it feel more natural to have frames as column, and if I remember well that's what BTK was doing - it's more convenient for MATLAB plotting for example (personal opinion).
In any case this was more of a personal curiosity, thank you for the explanation!
