### ISSUE TITLE
Python import ezc3d error

### ISSUE THREAD

**Issue by mrrezaie** [pyomeca/ezc3d#201]
Hi,

I was using ezc3d in Python without any problem. After appending OpenSim4.2/bin folder to my system environment path, this error appears: 

---> 13     from . import _ezc3d
ImportError: DLL load failed: The specified procedure could not be found.

I see that there is a file named ezc3d.dll in that folder. After renaming this file, Python imports ezc3d properly.

Is there any workaround to fix this issue without changing any file name or keeping only one library in system path?

Any help is much appreciated.

Regards,
Mohammadreza

**Comment by pariterre** [comment]
Hi @mrrezaie 
That is weird since the CMake is supposed to take this into account... That said, the fact that you are using OpenSim concurrently may create a more exotic installation pipeline.
I suspect that in Osim the expected file name is ezc3d.dll while it is _ezc3d.dll when installing ezc3d for yourself. 

My guess is that you actually have found the workaround

**Comment by mrrezaie** [comment]
Thanks for your reply.
