### ISSUE TITLE
Could you give an example of setting timecode in Python?

### ISSUE THREAD

**Issue by sineadkearney** [pyomeca/ezc3d#209]
Hi, 

I can't get the starting timecode to work in Vicon shogun. As an example, I manually export the c3d data from Vicon, which has a particular timecode. Then I python I have:

```
import ezc3d
c3d = ezc3d.c3d('path/to/manually/exported/data.c3d')
c3d['parameters']['POINT']['UNITS']['value']=[]
c3d.write('path/to/manually/exported/data_new.c3d')
'''
c3d['parameters']['POINT']['UNITS']['value'] was ['mm']

This gives the following error in Shogun:
ERROR: Script error on line 2.
ERROR: Failed to load path/to/manually/exported/data_new.c3d
ERROR: Invalid number of dimensions for analog scale value
'''
```

I then load this new c3d file into Vicon and the starting timecode is always 0.

Thanks,
Sinead

**Comment by pariterre** [comment]
Hi  @sineadkearney 
This actually look like a bug in my code and not in yours. Is that possible to send me one c3d file before and after the conversion? So I could have a deeper look of what changed.
You can drop it here, or to me personally at pariterre@hotmail.com

Thanks!

**Comment by pariterre** [comment]
Hi @sineadkearney 
Sorry for my late response!
I think I've found the bug... What happens is if the ANALOG:SCALE is empty, if automatically fills it with the right size with the value in the header, which is the expected behavior in a C3D (things should not be stored in the header, but in the parameters). But it seems that Shogun expect SCALE not to be defined if empty, even though they define something in the header... I created a (sad) patch that introduces the same bug as in Shogun into ezc3d to conform with their implementation (PR #210). 
Please let me know if the fix worked! (Did you install via conda or you compiled by hand? If the former, I will have to create a release so you can update. Let met know, otherwise, I will wait you confirm that it works before releasing :) )

**Comment by sineadkearney** [comment]
Thanks for working on this issue. I use conda to install the library, so if you could make a release with the new change, that would be really helpful.

**Comment by pariterre** [comment]
@sineadkearney 
Just so you know, I released a new version right after your last comment :)
You can have a try!

**Comment by sineadkearney** [comment]
Could you give me the steps on how to get the latest version of ezc3d? I was having issues with updating in my environment so I created a new one and did the following:

```
conda create --name ezc3d
conda activate ezc3d
conda install -c conda-forge ezc3d
python:
import ezc3d
print(ezc3d.__version__)

```
this gives me 1.4.3 but I think it should be 1.4.5 (and the timecode is still at 0 when I import into Shogun)

**Comment by pariterre** [comment]
Oh! I forgot to change the version tag inside ezc3d!
If you type :
conda list
You should see that your version is indeed 1.4.5 

Sorry about that!

**Comment by pariterre** [comment]
> and the timecode is still at 0 when I import into Shogun

Ok I'll have another look then. I keep you posted
