### ISSUE TITLE
Extra data extracted

### ISSUE THREAD

**Issue by mrrezaie** [pyomeca/ezc3d#219]
Hi @pariterre,

I have a c3d file exported from Vicon Nexus that there are many other information and analyses such as virtual markers, joints angle, force, moment and power stored in that. My problem is that when I use the following script, all these information come with marker data.

LABELS= c['parameters']['POINT']['LABELS']['value']
POINTS= c['data']['points']

Is there any way to extract just the markers data?
[task;xzy;r2;l1.zip](https://github.com/pyomeca/ezc3d/files/6997070/task.xzy.r2.l1.zip)

Also, the number of LABELS and POINTS are different.

Thank you in advance,
Mohammadreza

**Comment by pariterre** [comment]
Hi @mrrezaie 
As you are using it, `ezc3d` is merely a reader that gives you access to the binary format of a `c3d`. Unfortunately, there is no standardized way to write a c3d, except for very specific structures. That means that Vicon probably fit in extra data in the c3d that initially intended by the standard. It is therefore hard to propose a good solution for your problem since it depends on the decision made by Vicon themselves. 

I had a look at your file and I am not sure why `c["data"]["points"].shape[1]` and `len(c["parameters"]["POINT"]["LABELS"]["value"])` are not equal. However, again, this is a decision made by Vicon, on which I have very few power...

If it were me, I would simply plot everything in a 3d space to isolate the markers and the rest, so I could understand how Vicon stored the value. My first guess is that the first rows of the data point matrix are the real marker, but I am a bit confused for the remaining columns...

**Comment by mrrezaie** [comment]
Thanks for your reply.

Regarding the length of labels, I found that there are two sets of labels:
`LABELS = c['parameters']['POINT']['LABELS']['value'] + c['parameters']['POINT']['LABELS2']['value']`
Now the length of LABELS and POINTS are identical. 

I decided to remove the Irrelevant data in MOKKA, but a bit time consuming.

**Comment by pariterre** [comment]
Yep that make sense! Sorry I did not notice that there were more than 255 LABELS (this is the maximum one LABEL can hold). 

Since they are now the same length, I would feel confident simply slicing the data if I were you. Meaning that you can do :
```python
markers = c["data"]["points"][:, :nb_markers, :]
```
to extract the marker part of the points in the data. That will save you a lot of time I think!

**Comment by mrrezaie** [comment]
I appreciate your help.
