### ISSUE TITLE
ezc3d, Mokka and firsframe > 1

### ISSUE THREAD

**Issue by A-Tomezzoli** [pyomeca/ezc3d#224]
It seems that ezc3d do not take into account in the same way "c3d.header.points.firstFrame" while writting (or reading) new "c3d.data.points" versus new "c3d.parameters.EVENT.TIMES.DATA". 
When reading these new data using MOKKA, there is in a gap between events and curves plotted from the points.
In the same way, when events are created using MOKKA and then red using ezc3d, there is a gap between events and curves.
I thing the issue commes from ezc3d not from MOKKA, because  events created using MOKKA and then red using VICON-NEXUS stay in the right place.
Of course it is easy to go round this problem, but maybe it could be interesting to fix it in ezc3d?

**Comment by pariterre** [comment]
Dear @A-Tomezzoli !
Thanks for reporting! There is still work to do with the events in ezc3d as I never used them myself.. I will have a look at this in the upcoming weeks/months. Unfortunately, as I am currently at the end of my PhD, I won't have much time in the short term, but definitely will have a look afterwards!

Thanks again :)

**Comment by Svito-zar** [comment]
Any updates on this issue? I experience exactly the same problem now.
@A-Tomezzoli what is the easy way to solve it? @pariterre do you have time for it now?

**Comment by pariterre** [comment]
Hi @Svito-zar 
I probably have a bit of time for that!
Could you provide me with a c3d that I can test with, and maybe one or two screenshots so I can diagnose the problem :)


Thanks!

**Comment by Svito-zar** [comment]
My issue is that when I read a c3d file and write back exactly the same data I get a one-frame mismatch.

I uploaded example c3d files in [this Google Drive folder](https://drive.google.com/drive/folders/1tbT5sNjtsuxeTzbHA7AT_foDJGlufKks?usp=sharing).

And below are a few screenshots illustrating the issue

![both_together](https://user-images.githubusercontent.com/15908492/204602774-f8fa5eaf-6299-4553-bd44-da768437d517.png)



![original](https://user-images.githubusercontent.com/15908492/204602864-819509ae-e2c5-4c61-806c-711cef6b6052.png)



![processed](https://user-images.githubusercontent.com/15908492/204602899-f7608ee4-3757-4a34-acf7-85ece1ac1df2.png)

**Comment by Svito-zar** [comment]
@pariterre, please let me know if you need any further information from me

**Comment by pariterre** [comment]
Dear @Svito-zar 

Sorry for the late answer, my December has been much busier than expected. I had a look at your file. At first, it got me confused for a while as I could not see anything wrong with the processed c3d. The reason is: there is in fact nothing wrong with it. The main issue comes from the way companies has implemented their c3d writer (i.e. not complying with the standard). 

In your case, it seems that your original c3d has its first frame tagged as "0". But for some reason, the c3d standard is that first frame is 1 (1-base instead of 0-base). We all agree this makes no sense, but still this is the way it should be stored. Ezc3d complies to that formating and will actively correct the mistake in the c3d (so changing the 0 for a 1). Doing so, the software you showed will interpret the first frame as being 1 instead of 0, and therefore creating a discrepancy. 

I suspect this is the same @A-Tomezzoli experienced as I know that Mokka (actually BTK) does minimal changes to c3d writing a new one (i.e. keeping an invalid c3d if they were invalid in the first place), while my approach is to correct any error in a c3d in order to produce a valid c3d. The reason I choose to do so is that the newly produced c3d is now fully compliant with the standard and can therefore be read by all software. 

I therefore feel there is not much to do about this discrepancy... :S

**Comment by Svito-zar** [comment]
@pariterre, thank you for your answer!
What if I want to have it 0-base? Could there be a flag for me to enable that in Ezc3d, like `enable_zero_base=True`?

**Comment by pariterre** [comment]
Hi @Svito-zar 
I pushed a fix (PR #279 ) that should do the trick. I need to wait the tests pass, then I can release it to conda-forge. The way to use it would be use `parametrizedWrite` instead of `write` 

Hope this helps ;)

**Comment by Svito-zar** [comment]
Thank you so much, @pariterre for making this happen!

**Comment by pariterre** [comment]
@Svito-zar 
I'll close this issue, please do not hesitate to coming back to me if there is anything!
