### ISSUE TITLE
octave: regardless of version?

### ISSUE THREAD

**Issue by pauk98** [pyomeca/ezc3d#226]
Hi,

With your help I was able to compile the ezc3d codes for octave. Since then, I use this tool, and it works great for me so far. (As far as I know, it's the only toolbox which supports octave to open c3d files...).

I'm using octave version 6.2.0 and ezc3d version 1.4.0.
If I send my octave skripts including the ezc3dRead function (with the compiled ezc3d folder) to another person who uses the exact same version of octave it works perfect on their computer. Some days ago I noticed, that this isn't  the case, if there is another version of octave installed on their computer (f.e. 4..1.0 or 6.4.0) or using the online version on CoCalc (6.3.0). 

error: /home/user/mastterseminar_WS21_22_skripts/ezc3d/ezc3dRead.mex: failed to load: /home/user/mastterseminar_WS21_22_skripts/ezc3d/ezc3dRead.mex: invalid ELF header
 error: called from mM_synergies_highlow at line 66 column 11

I'm trying to implement ezc3d as the standart tool on our university, cause it works on octave as a free software for students, which is fine. Cause the ezc3dRead function isn't working with the new octave versions, my solution was, to install octave version 6.2.0 for students, but this is a unsatisfying long term solution.

My question is, if there is a possibility to get codes which are regardless of the octave version? So it is not necessary, to compile ezc3d every time when updating the software... (this produced new errors when I tried it out, I'm not very familiar whith VS).
Maybe this exists, but I was unable to find it. Or it is possible if using miniconda, but this also produces errors (I'm also not familiar with miniconda).

best wishes, paul

**Comment by pariterre** [comment]
Dear @pauk98 
I am glad you can enjoy ezc3d :)

There is unfortunately no satisfying solution for the problem you describe. Python solved this problem by automatically recompile every single package for every version, but making this easy to install (more specifically using Anaconda or pip). Hence, it is easier to maintain.  Octave (and Matlab), did not provide easy to compile solution. One solution could have been using Anaconda as well, but noone made Octave available on conda-forge for Windows, which makes this at best a partial solution. Moreover, it seems that octave is not well maintained as the last version seems to be 6.3.0 (again only for Unix). 

As far as I concerned, the best solution is the one you described, that is recompiling for every version by hand. This is precisely why I do not provide myself the binaries for Matlab or Octave, it would put to large of a burden on me... 

For the specific question if it is possible to compile some sort of generic version, the answer is totally dependent on how Octave works. Since I don't use it myself (I made an Octave version out of my Matlab binder with very few modifications), I have no clue how to optimize for Octave specifically. My first guess though is that each library is bound to a specific version and there is nothing we can do against that. If you are on Windows, I'd be even more positive on this as Windows is VERY sensitive to the version of a library, not only for Octave, but on any library linkage on this OS.

Hope this answer helps even though it is not so much satisfying...
