### ISSUE TITLE
Not able to install octave binaries

### ISSUE THREAD

**Issue by jobingthampi** [pyomeca/ezc3d#247]
![ezc3d](https://user-images.githubusercontent.com/105680380/168877039-262802c4-316c-4394-a3c0-be0d400943ce.jpg)
I have attached the image and this is the issue I get when I try to install octave binaries.

**Comment by pariterre** [comment]
Hi @jobingthampi 
It seems that you are running Windows. Unfortunately, the octave binaries are not availble for windows on conda, therefore I cannot precompile the ezc3d octave binaries. You have to compile them for yourself (as shown in the video we discussed on, on Youtube)

**Comment by jobingthampi** [comment]
In youtube i saw your video that you are compiling using cmake, but they will ask for the source code and I am not able to get that , in your ezc3d file I saw file named srs but here I don't have.
![image](https://user-images.githubusercontent.com/105680380/168881447-4e004bf8-8692-4111-a363-ac3183726ebc.png)

**Comment by pariterre** [comment]
The source code is here (I mean here in github (https://github.com/pyomeca/ezc3d) ), that is the very purpose of GitHub to hold source code ;) 

What you are looking at, are the header files of the C++ code that are delivered with the compiled version. That is useless to you unless you want to develop in C++, which I don't think you want. 

As a piece of advice, you should basically forget about anaconda at all because it is not required nor useful to compile ezc3d.

**Comment by jobingthampi** [comment]
![image](https://user-images.githubusercontent.com/105680380/168897602-99c86157-c63c-4e69-8998-1c54cc34da07.png)
why is this error happening?

**Comment by pariterre** [comment]
The error message is actually in the lower part of the window behind (where it is written "Configuration incomplete", just scroll up). But since it failed so early, I suspect that you don't have a compiler installed on your computer. Here you are trying to bound your compilation to "Visual Studio 17 2022" but it has to be installed on the computer in the first place 
https://visualstudio.microsoft.com/fr/vs/older-downloads/

Download the community version which is free and install things related to C++ and Desktop application

**Comment by jobingthampi** [comment]
![image](https://user-images.githubusercontent.com/105680380/168954814-5cc87188-2dc9-468b-8631-c3ab8bc58b19.png)
Hi i installed Visual studio 2022 still the error is happening!

**Comment by jobingthampi** [comment]
![image](https://user-images.githubusercontent.com/105680380/168955184-9b44d660-ec4f-489f-a0a2-b58b9da92bc7.png)

I attached the image hereby

**Comment by pariterre** [comment]
@jobingthampi 
You have to show me the actual error so I can help. As I said, the error message is in the window where it is written "Configuration incomplete". I still have no clue what error you get...

**Comment by jobingthampi** [comment]
Sir , like you told I downloaded the files from GitHub and then I installed Visual studio 2022 version and when I tried to compile it using Cake this is the error iam getting.

**Comment by pariterre** [comment]
The error dialog you showed me IS NOT the actual error message. The error message is in the output of the window behind it (where it is written "Configuration incomplete, ..."). The error message part is now hidden because the box that contains it is so tiny. You can scroll up this output to make the message appear and do another screenshot (or copy-paste it) so I can know what the error actually is! I am sorry, I do not know how to say it more clearer. If you don't provide me with the actual error message (not the generic dialog that tells there is an error), I can't help you.

**Comment by jobingthampi** [comment]
![image](https://user-images.githubusercontent.com/105680380/169097849-838005b9-5cce-4e0c-a710-8b28f68c45f9.png)
![image](https://user-images.githubusercontent.com/105680380/169097955-d3d5fefd-6bc3-4be6-82d2-2c0e0dfc2e0e.png)
I have attached the screenshots of it, but I have installed visual studio on my laptop.

**Comment by pariterre** [comment]
https://stackoverflow.com/questions/51668676/cmake-visual-studio-15-2017-could-not-find-any-instance-of-visual-studio

**Comment by pariterre** [comment]
Dear @jobingthampi 
I figured that we would both save a lot of time if I would provide you with the compiled version already. So I installed everything (I do not use a Windows computer myself, not for programming at least). Please find attached a compiled version of ezc3d last version. Hopefully this will suit you!
[ezc3d.zip](https://github.com/pyomeca/ezc3d/files/8718651/ezc3d.zip)

**Comment by jobingthampi** [comment]
![image](https://user-images.githubusercontent.com/105680380/169113339-8624cbcb-d03e-45ea-88d9-53edc133b841.png)
![image](https://user-images.githubusercontent.com/105680380/169113490-eb22ebbf-b87b-4235-ae8a-cfc4b2f53445.png)
i got your compiled version and did like you showed in the video, but still matlab is giving error

**Comment by pariterre** [comment]
My bad, I gave you the octave binaries

Here are the Matlab ones!
[ezc3d_matlab.zip](https://github.com/pyomeca/ezc3d/files/8719294/ezc3d_matlab.zip)

**Comment by jobingthampi** [comment]
Hi, I am getting the same error. So previously what I did was the .mex files(Octave binaries) were renamed by .mex64 and changed to Matlab format. Now, you send me the same Matlab version. so errors in both cases are the same.

**Comment by pariterre** [comment]
Which version of Matlab are you using? I have compiled the file using Matlab_2022a. Obviously it can't be used with previous versions (that is precisely why I do not usually provide the binaries myself as it requires to build a bunch of them)

**Comment by jobingthampi** [comment]
iam using Matlab R2022a

**Comment by jobingthampi** [comment]
![image](https://user-images.githubusercontent.com/105680380/169142677-35d34665-7fb4-477c-8d0f-108c2eb69658.png)

**Comment by pariterre** [comment]
Are you sure you actually used the `_matlab` version? I tried to download it from the link I gave you and it worked just fine... If you had to rename the file, you definitely used the wrong zip file..

**Comment by jobingthampi** [comment]
yes you can see in the screenshot I posted

**Comment by jobingthampi** [comment]
Renaming the file was done for file for the octave version. I haven't renamed the file (Matlab) which you recently sent me.

**Comment by jobingthampi** [comment]
![image](https://user-images.githubusercontent.com/105680380/169144090-d3984cce-d593-4e51-bd3d-0bc82c089ebd.png)
This is the path

**Comment by pariterre** [comment]
According to google it seems that this can be caused by invalid compatilibity between the compiler and the RunTime compiler of Windows. I'll see if I can compile with another version of Visual Studio

**Comment by jobingthampi** [comment]
Ok

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pariterre** [comment]
Third time the charm. This one was generated with Visual Studio 17 2022 and Matlab R2022a. You should be able to run it
[ezc3d_matlab.zip](https://github.com/pyomeca/ezc3d/files/8729054/ezc3d_matlab.zip)
!

**Comment by pariterre** [comment]
For those who would see this thread in the future, octave binaries are now available on conda for macosx and linux

**Comment by jobingthampi** [comment]
Oh got it, so first I should download all these files in zip format then extract and then follow the videos, am I right?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pariterre** [comment]
You won't have to follow the video :) The resulting binaries of the video is what I zipped. So you just extract in a folder seen by matlab (using addpath to the path you extracted) and it should work :)
