### ISSUE TITLE
Error Installing Octave Binary 

### ISSUE THREAD

**Issue by ihasan2** [pyomeca/ezc3d#267]
Hi, 

I'm trying to install the ocatve binary by running this command (conda install -c conda-forge ezc3d=*=*octave*) and I keep getting this error message.

PackagesNotFoundError: The following packages are not available from current channels:

  - ezc3d[build=*octave*]

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by pariterre** [comment]
Dear @ihasan2 

Can you confirm that you are not running on Windows? As stated in the documentation, the precompiled binaries are not on conda-forge for Windows. This comes from the fact that "octave" itself is not on conda on Windows. Therefore, you either have to run on Linux or Mac. Otherwise, you will have to compile ezc3d for yourself.
