### ISSUE TITLE
Convert csv / pickle to c3d

### ISSUE THREAD

**Issue by mfalv** [pyomeca/ezc3d#275]
Is there a way to convert a csv / pickle file to c3d?

**Comment by pariterre** [comment]
Hi @mfalv 

There is no automated way to do that, however, creating a brand new c3d and pushing data to it actually not complicated. 

If you have a look in the readme section Python (if you are in Python) or Matlab (if you are in Matlab) you can see how creating and adding data to a c3d
https://github.com/pyomeca/ezc3d#python-3
The relevant part is:
```python
import ezc3d

c3d = ezc3d.c3d()

c3d['parameters']['POINT']['RATE']['value'] = [100]
c3d['parameters']['POINT']['LABELS']['value'] = ('point1', 'point2', 'point3', 'point4', 'point5')
c3d['data']['points'] = np.random.rand(4, 5, 100)

c3d.write("path_to_c3d.c3d")
```
Since POINT:RATE and POINT:LABELS must be supplied along with the actual data in order to produce a valid C3D.

I hope this helps!

**Comment by mfalv** [comment]
Thanks @pariterre , that helps a lot!
I run into an issue however: whenever I attempt to use "write" to save the c3d file, it fails to do so and I get the error message presented below. Is there a way to overcome this?

TypeError: Wrong number or type of arguments for overloaded function 'c3d_point'.
  Possible C/C++ prototypes are:
    ezc3d::c3d::point(std::string const &)
    ezc3d::c3d::point(std::string const &,std::vector< ezc3d::DataNS::Frame,std::allocator< ezc3d::DataNS::Frame > > const &)
    ezc3d::c3d::point(std::vector< std::string,std::allocator< std::string > > const &)
    ezc3d::c3d::point(std::vector< std::string,std::allocator< std::string > > const &,std::vector< ezc3d::DataNS::Frame,std::allocator< ezc3d::DataNS::Frame > > const &)

**Comment by mfalv** [comment]
It does help! Thanks @pariterre .
