### ISSUE TITLE
the c3d file dont open

### ISSUE THREAD

**Issue by redcat22** [pyomeca/ezc3d#48]
HI 

Iam trying to read a c3d but I'm getting the following error:
Exception has occurred: RuntimeError
vector T too long

Note that I just used this code:
from ezc3d import c3d Test2 = c3d('D:\\H_Walk_001.c3d')

Note that I collected data during 14 minutes at 100 Hz therefore I have around 90000 frames in each file.
All my files demands large number of frames to be able to perform non linear analysis therefore the files should be able to support higher vectores. Would be possible to solve this issue please.

**Comment by pariterre** [comment]
Hi!
Could you provide me with a c3d? Either you can drop it on a downloadable link or do a pull request https://github.com/pyomeca/ezc3d_c3dTestFiles

I could create it myself, but the C3D format as described by c3d.org doesn't allow for that amount of frames. So, your case is probably specific to the system you used to acquire them. As soon as I have a patch, I push it and notice you!

**Comment by redcat22** [comment]
HI,

Thank you very much., The file is in wetransfer (132 mb) you can get it here:
https://we.tl/t-jFqzmvIVJQ

I acquire the data with vicon nexus.
cheers

**Comment by pariterre** [comment]
There you go, Update to the 0.3.5 (conda update) and it should do the trick :)

**Comment by redcat22** [comment]
Thank you pariterre

Note: the tests were made with the file that I send you.
However I still found some errors (I will take a look in more detail when I have a litle of time but for now i detected this issues:

```
#Data retrieved like thiss:
acq = c3d(os.path.join(fullPath, fileName))         # returns a handle to RetrieveC3DDada
TRIAL_ACTUAL_END_FIELD = acq['parameters']['TRIAL']['ACTUAL_END_FIELD']['value']
Points_FRAMES= acq['parameters']['POINT']['FRAMES']['value']
```
The TRIAL_ACTUAL_END_FIELD is wrong it gives a value of 24542 when it should be 90078 (for the file that I send you)

The Points_FRAMES also sems wrong according to this information https://www.c3d.org/HTML/default.htm this should be calculated in this maner last_frame – first_frame +1

In the file thaat I sent you:
first_frame =1
last_frame = 90078
result should be  90078  but we get 90079

Note: I edited the text because i noticed that one assumption that I made about one c3d parameter was wrong

**Comment by pariterre** [comment]
Hi there!
Here are some explanation on what is going on under the hood : 
TRIAL_ACTUAL_END_FIELD : is, by standard, an int coded on 4-bits. This give a maximal value of 0xFFFF = 65535. The value that you get is the real value modulo 0xFFFF. This was actually the same problem with the first update I've made. However, there is no elegant way to solve that. I could interpret the value as the last nearest value to the max, but if you sliced more that 0xFFFF data, the value will be plain wrong. Moreover, this is an in-house Vicon work-around.... It seems touchy to implement an actual workaround without introducing potential major bug (by design). That was possible for the parameter "FRAMES" of group "POINT" since the put the value -1 which I interpret as the whole file. May I suggest that I don't make modification for this particular issue and that means you would have to interpret this value (by adding 0xFFFF if necessary)?

DATA_START is a flag to tell the programmer where the data start in the c3d file, it has nothing to do with what frame. To know the actual first frame, you should read if from the header.

Finally POINT:FRAMES is the total number of frame and not what is the last frame. Therefore, it is last_frame + 1. So it is normal that it gives 90079

Hope this clarify few things!

**Comment by pariterre** [comment]
Oh, I just wrote while you were changing the comment. 

The first frame is not 1, it is 0 (the number are given in 0 based values)

**Comment by redcat22** [comment]
Hi pariterre 

Thanks again. 
While you answer I was also editing my initial post regarding the DATA START.
What to you mean by "by adding 0xFFFF if necessary" In python how can I get the real TRIAL_ACTUAL_END_FIELD adding 0xFFFF ?

**Comment by redcat22** [comment]
But that is strange in another file I get (in vicon) the values of first frame 10 and last frame 5724 
therefore I get 5724 - 10 + 1 = 5715 (which seems correct with your code)
so why when I get in other file first frame=1 last frame=90078 this would give 90079 and not 90078 ? 
This make sense?

**Comment by pariterre** [comment]
Hello, 

I actually mean the same as I would do, but knowing that it happens : 
For example, if you have a value of END_FIELD = 24542, that means the real value is either : 24542 or 24542 + 65535 = 90077. I, as the programmer, I no clue if you really wanted 24542 or if you meant 90077. This is something only you can know (I can make some assumption, but these assumptions will be false sometime, e.g. if I make the assumption that you wanted 90077, but really meant 24542). For now, the solution is to give you what is actually in the c3d file and let you interpret it as you prefer.

**Comment by pariterre** [comment]
For you second question : 
Because the tag ACTUAL_START_FIELD given by Vicon can be misleading. The real value for the first frame when you don't slice your data is 0 and not 1.

**Comment by redcat22** [comment]
pariterre, thank you very much for the clarification.

**Comment by pariterre** [comment]
If these answer all your questions, I suggest that you mark the issue as resolve :) Otherwise, you can leave it open or if you plan to ask other questions related to this issue!
