### ISSUE TITLE
return only specified columns/index

### ISSUE THREAD

**Issue by romainmartinez** [pyomeca/ezc3d#78]
When you already know the channel names you want extract from a c3d, speed and memory footprint could be optimized if ezc3d return only the specified columns/index. 

For example, when paired with Delsys, Vicon creates a large number of empty analog channels that increase memory usage for nothing.

**Comment by pariterre** [comment]
Do you talk about the Python interface or the actual core?

**Comment by romainmartinez** [comment]
I guess it will be faster to implement it in the ezc3d core. However, I don't know if you can parse the channel names first and then read only the corresponding data as I'm not really familiar with the internal implementation.

In python, I implemented this:

```python
def read_c3d(
    filename: Union[str, Path],
    usecols: Union[int, str, list] = None,
    prefix: str = None,
) -> Array:
    reader = ezc3d.c3d(f"{filename}").c3d_swig

    channels = [
        label.split(prefix)[-1]
        for label in reader.parameters()
        .group("ANALOG")
        .parameter("LABELS")
        .valuesAsString()
    ]

    if usecols is None:
        data = reader.get_analogs()
        channels_used = channels
    else:
        if isinstance(usecols, int):
            idx = [usecols]
        elif isinstance(usecols, str):
            idx = [channels.index(usecols)]
        elif isinstance(usecols, list):
            if isinstance(usecols[0], str):
                idx = [channels.index(channel) for channel in usecols]
            elif isinstance(usecols[0], int):
                idx = usecols
            else:
                raise ValueError("values inside usecols must be int or str")
        else:
            raise ValueError("usecols must be int, str or a list")

        data = reader.get_analogs()[:, idx, :]
```

**Comment by pariterre** [comment]
Ok, I'll have a look if I can implement this in the core... Like that I could create the release GetWhatYouWant B-)

**Comment by romainmartinez** [comment]
This is just an idea and a "nice to have" feature. `GetWhatYouWant` could be release anytime :)

**Comment by pariterre** [comment]
Hi @romainmartinez 
I've had a longer thought about that and because of the way LABELS, DESCRIPTION are stored it makes this very complicated. Mostly because some software, don't fill these parameters properly. If I just have to read them, even though they are poorly written, it works, but if I have to skip some markers (because a list would have been provided), then I have to properly parse these parameters. 

I therefore think it falls in data analysis, which I do not want to go in with ezc3d. I think splicing using pyomeca is then the right way to do it, even though it costs a bit of time

Thanks for the suggestion!
