### ISSUE TITLE
Add more detailed developers documentation

### ISSUE THREAD

**Issue by marnunez** [pyomeca/ezc3d#82]
I've just cloned the repo to do some testing, and I'm having some trouble figuring out how gtest works or where (or if) a setup.py is generated. The cmake part of it was pretty straight forward (OpenSIM toolchain is a harsh teacher hehe).

**Comment by pariterre** [comment]
Hahaha! 

For gtest, it is supposed to be straight forward, but you cloned ezc3d the only day it is not!

I've notice that I included a 3Mb folder that should not be there a week ago, and I corrected the repo in a destructive manner. However, doing so, it also removed the gtest submodule.

Usually, if you run CMake, it will download and compile gtest by itself, but it fails today because of this! Since. I was working with a colleague on something else (I did not planned that someone else would clone today!), I did not corrected it yet...

I should push the gtest submodule tomorrow, and therefore it should work out-of-the-box again...

Sry about that!

**Comment by marnunez** [comment]
No worries! Just wondering weather the BTS c3d passes all normal tests. C++ is definitely not my thing...

**Comment by pariterre** [comment]
Hi @marnunez 
I just had a check on the repo and everything should be fine now. 
Quick question, when you say to explain how gtest works, do you mean having an actual part of the ReadMe explaining how to use EXPECT macros or you mean how to make it compile and run?

**Comment by pariterre** [comment]
Also, I just made the fact that the c3d are taken from github instead of having them in the repo. 
Please note that because of the changes made, the repo won't fit anymore (this is highly unusual, but it is necessary when deleting history of a file from git). Meaning that you should actually delete your fork and redo it then incorporate your changes afterward (otherwise, it will bring that the files I removed :P )

**Comment by marnunez** [comment]
> Hi @marnunez
> I just had a check on the repo and everything should be fine now.
> Quick question, when you say to explain how gtest works, do you mean having an actual part of the ReadMe explaining how to use EXPECT macros or you mean how to make it compile and run?

I was thinking the latter. You know, how and where the runUnitTests binary is created, remind users to add the files to PATH, etc. The EXPECT macro was surprisingly intuitive.

> Also, I just made the fact that the c3d are taken from github instead of having them in the repo.
> Please note that because of the changes made, the repo won't fit anymore (this is highly unusual, but it is necessary when deleting history of a file from git). Meaning that you should actually delete your fork and redo it then incorporate your changes afterward (otherwise, it will bring that the files I removed :P )

Found out the hard way, when "no history was shared" between my fork and upstream hehe. Remade the fork and that was that, no troubles.

**Comment by pariterre** [comment]
Hi!
I added some explanation in the ReadMe, but wasn't sure what to write exactly.. Hopefully, this is enough!
