### ISSUE TITLE
nonConst version of member functions missing (documentation error?)

### ISSUE THREAD

**Issue by lasagnaphil** [pyomeca/ezc3d#99]
I was trying to modify some points in a c3d file, and the current README.md suggests to use a nonConst member function to do this elegantly. However I couldn't find any of those non-const member functions in the library. Am I doing something wrong here, or is the documentation outdated?

P.S. What I was trying to do was to scale all the points by a certain ratio, and I could do it in a one-liner in Python:

    c['data']['points'] *= scale

Is there any straightforward way to do this in C++?

**Comment by pariterre** [comment]
I am really sorry, I completely forgot to answer your question. If it happens ever again, feel free to ping me again!

Indeed, nonConst has been removed, but I forgot to change the readme, thanks for pointing it out. 

There is no currently implemented method to operate directly on points, but I think it is a good idea, I will definitely consider it (simple operation like additions and multiplications). In any case, it can't be a one liner though (It has to be a 3 liners in a for loop), because there are parameters that must updated when changes are made to the data... 

The following code shows you how to change the value of a point. The interesting bit are the three lines near the end. Everything before is just to create a valid c3d with a single frame and a single point in it. 
```C++
// Create an empy c3d
ezc3d::c3d c3d;

// Fill create a new point in the file
ezc3d::ParametersNS::GroupNS::Parameter pointRate("RATE");
pointRate.set(std::vector<float>() = {100}, {1});
c3d.parameter("POINT", pointRate);
c3d.point("my new point");
ezc3d::DataNS::Frame frame;
ezc3d::DataNS::Points3dNS::Points pts_new;
ezc3d::DataNS::Points3dNS::Point pt_new;
pt_new.set(1., 2., 3.);
pts_new.point(pt_new);
frame.add(pts_new);
c3d.frame(frame);

// Print the current value ==> (1, 2, 3)
c3d.data().frame(0).points().point(0).print();

// Change its value (the interesting bit)
ezc3d::DataNS::Frame frameTochange(c3d.data().frame(0));
// Make every change you want to on this frame here...
frameTochange.points().point(0).set(4., 5., 6.);
c3d.frame(frameTochange, 0);

// Print its new value ==> (4, 5, 6)
c3d.data().frame(0).points().point(0).print();
```

If I were to add operation, the only thing it would change would be the `frameTochange.points().point(0).set(4., 5., 6.);` where it could read something like `frameTochange.points().point(0) *= 2;` in the case you wanted to scale by a factor of 2!

Hope it helps! Sorry again for the delay!

**Comment by pariterre** [comment]
The documentation has been corrected! Thanks
